### ISSUE TITLE
pulp-npm currently doesn't install, still reporting requirements pulpcore>=3.11,<3.13

### ISSUE THREAD

**Issue by gpavinteractiv** [pulp/pulp_npm#188]
**Version**
pulp_installer 3.20.0
pulpcore 3.20
pulp_npm Release 0.1.0a3

**Describe the bug**
pulp installation with ansible, with pulp-npm plugin selected, fails at requirements check : pulpcore~=3.20 & pulpcore>=3.11,<3.13

According to the following link, plugins need to be updated/released with new requirements : https://discourse.pulpproject.org/t/pulpore-3-20-planned-for-june-21st/465/8

````
The 3.20 is now available on PyPI, however it requires every plugin to release a compatible release. 
Pulpcore 3.25 is the next "plugin API breaking changes release, 
so all plugins should likely declare their compatibility as pulpcore>=3.20,<3.25.

Plugins could also declare older compatibility if that’s truly the case, 
but the forward compatibility should definitely be through 3.24.
````

**Comment by mdellweg** [comment]
We just released pulp_npm 0.1.0a4, can you recheck and close this issue?

**Comment by gpavinteractiv** [comment]
Install through pip still fails.
Pip is still pulling 0.1.0a3, even though the release was made 13h ago and visible on pypi.org : 
````
Collecting pulp-npm
  Downloading pulp_npm-0.1.0a3-py3-none-any.whl (32 kB)
````

pulp_install with ansible fails similarly at :
````
TASK [pulp.pulp_installer.pulp_common : Run pip-compile to check pulpcore/plugin compatibility] ********************************************************************************************************************************
task path: /home/ansible/.ansible/collections/ansible_collections/pulp/pulp_installer/roles/pulp_common/tasks/preflight_function.yml:36

        "There are incompatible versions in the resolved dependencies:",
        "  pulpcore~=3.20.0 (from -r requirements.in (line 1))",
        "  pulpcore<3.22,>=3.16.0 (from pulp-rpm==3.17.6->-r requirements.in (line 3))",
        "  pulpcore<3.13,>=3.11 (from pulp-npm==0.1.0a3->-r requirements.in (line 2))"
````

- If I edit that task to not fail (ignore_error: yes)
- and do a manual install of the pulp-npm .whl package with pip
- Then pulp ansible installation works for me

**Comment by decko** [comment]
Hi @gpavinteractiv, we just released a new version of pulp_npm and published it to Pypi. 
Also, the `pip index versions pulp-npm` now is showing a proper return:
```
 ~ ❯ pip index versions pulp-npm
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
pulp-npm (0.1.0)
Available versions: 0.1.0
```

Also, the plugin installed without issues on pulpcore < 3.69.
I'm closing the issue for now, but feel free to reopen if you continue to face the issue, and join us on https://discourse.pulpproject.org/ for further discussions.
